# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: X:/Downloads/Nexys4DDR_Master.xdc

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/microBlaze/microBlaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze || ORIG_REF_NAME==microBlaze} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_microblaze_0_0/microBlaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_microblaze_0_0 || ORIG_REF_NAME==microBlaze_microblaze_0_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_dlmb_v10_0/microBlaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_dlmb_v10_0 || ORIG_REF_NAME==microBlaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_ilmb_v10_0/microBlaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_ilmb_v10_0 || ORIG_REF_NAME==microBlaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_dlmb_bram_if_cntlr_0/microBlaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microBlaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_ilmb_bram_if_cntlr_0/microBlaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microBlaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_lmb_bram_0/microBlaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_lmb_bram_0 || ORIG_REF_NAME==microBlaze_lmb_bram_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_xbar_0/microBlaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_xbar_0 || ORIG_REF_NAME==microBlaze_xbar_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_microblaze_0_axi_periph_0/microBlaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microBlaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_microblaze_0_axi_intc_0/microBlaze_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_microblaze_0_axi_intc_0 || ORIG_REF_NAME==microBlaze_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_microblaze_0_xlconcat_0/microBlaze_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_microblaze_0_xlconcat_0 || ORIG_REF_NAME==microBlaze_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_mdm_1_0/microBlaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_mdm_1_0 || ORIG_REF_NAME==microBlaze_mdm_1_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_clk_wiz_1_0/microBlaze_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_clk_wiz_1_0 || ORIG_REF_NAME==microBlaze_clk_wiz_1_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_rst_clk_wiz_1_100M_0/microBlaze_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microBlaze_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_mig_7series_0_0/microBlaze_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_mig_7series_0_0 || ORIG_REF_NAME==microBlaze_mig_7series_0_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_axi_uartlite_0_0/microBlaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_axi_uartlite_0_0 || ORIG_REF_NAME==microBlaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_mii_to_rmii_0_0/microBlaze_mii_to_rmii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_mii_to_rmii_0_0 || ORIG_REF_NAME==microBlaze_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_axi_ethernetlite_0_0/microBlaze_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_axi_ethernetlite_0_0 || ORIG_REF_NAME==microBlaze_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_axi_timer_0_0/microBlaze_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_axi_timer_0_0 || ORIG_REF_NAME==microBlaze_axi_timer_0_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_axi_smc_0/microBlaze_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_axi_smc_0 || ORIG_REF_NAME==microBlaze_axi_smc_0} -quiet] -quiet

# IP: bd/microBlaze/ip/microBlaze_rst_mig_7series_0_81M_0/microBlaze_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microBlaze_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==microBlaze_rst_mig_7series_0_81M_0} -quiet] -quiet

# XDC: bd/microBlaze/microBlaze_ooc.xdc
