# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_xbar_0/Ethernet_xbar_0.xci
# IP: The module: 'Ethernet_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_xbar_0/Ethernet_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_xbar_0/Ethernet_xbar_0.xci
# IP: The module: 'Ethernet_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_xbar_0/Ethernet_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
