# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_0/bd_9d5e_0_eth_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_9d5e_0_eth_buf_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_0/synth/bd_9d5e_0_eth_buf_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_9d5e_0_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_0/bd_9d5e_0_eth_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_9d5e_0_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_0/bd_9d5e_0_eth_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_9d5e_0_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_0/synth/bd_9d5e_0_eth_buf_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_9d5e_0_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_0/bd_9d5e_0_eth_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_9d5e_0_eth_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
