# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_mdm_1_0/Ethernet_mdm_1_0.xci
# IP: The module: 'Ethernet_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_mdm_1_0/Ethernet_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_mdm_1_0/Ethernet_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_mdm_1_0/Ethernet_mdm_1_0.xci
# IP: The module: 'Ethernet_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_mdm_1_0/Ethernet_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/Ethernet/ip/Ethernet_mdm_1_0/Ethernet_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
