# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/microBlaze_axi_smc_0.xci
# IP: The module: 'microBlaze_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/bd_9fcc.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_0/bd_9fcc_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_1/bd_9fcc_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_2/bd_9fcc_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_3/bd_9fcc_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_4/bd_9fcc_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_5/bd_9fcc_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_6/bd_9fcc_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_7/bd_9fcc_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_8/bd_9fcc_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_9/bd_9fcc_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_10/bd_9fcc_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_11/bd_9fcc_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_12/bd_9fcc_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_13/bd_9fcc_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_14/bd_9fcc_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_15/bd_9fcc_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_16/bd_9fcc_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_17/bd_9fcc_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_18/bd_9fcc_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_19/bd_9fcc_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_20/bd_9fcc_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_21/bd_9fcc_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_22/bd_9fcc_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_23/bd_9fcc_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_24/bd_9fcc_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_25/bd_9fcc_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_26/bd_9fcc_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_27/bd_9fcc_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_28/bd_9fcc_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_29/bd_9fcc_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_30/bd_9fcc_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_1/bd_9fcc_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_1/bd_9fcc_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_2/bd_9fcc_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_2/bd_9fcc_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_3/bd_9fcc_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_3/bd_9fcc_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_4/bd_9fcc_arsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_5/bd_9fcc_rsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_6/bd_9fcc_awsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_7/bd_9fcc_wsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_8/bd_9fcc_bsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_12/bd_9fcc_s00a2s_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_13/bd_9fcc_sarn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_14/bd_9fcc_srn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_15/bd_9fcc_sawn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_16/bd_9fcc_swn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_17/bd_9fcc_sbn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_21/bd_9fcc_s01a2s_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_22/bd_9fcc_sarn_1_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_23/bd_9fcc_srn_1_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_24/bd_9fcc_m00s2a_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_25/bd_9fcc_m00arn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_26/bd_9fcc_m00rn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_27/bd_9fcc_m00awn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_28/bd_9fcc_m00wn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_29/bd_9fcc_m00bn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microBlaze_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/microBlaze_axi_smc_0.xci
# IP: The module: 'microBlaze_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/bd_9fcc.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_0/bd_9fcc_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_1/bd_9fcc_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_2/bd_9fcc_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_3/bd_9fcc_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_4/bd_9fcc_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_5/bd_9fcc_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_6/bd_9fcc_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_7/bd_9fcc_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_8/bd_9fcc_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_9/bd_9fcc_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_10/bd_9fcc_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_11/bd_9fcc_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_12/bd_9fcc_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_13/bd_9fcc_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_14/bd_9fcc_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_15/bd_9fcc_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_16/bd_9fcc_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_17/bd_9fcc_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_18/bd_9fcc_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_19/bd_9fcc_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_20/bd_9fcc_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_21/bd_9fcc_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_22/bd_9fcc_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_23/bd_9fcc_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_24/bd_9fcc_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_25/bd_9fcc_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_26/bd_9fcc_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_27/bd_9fcc_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_28/bd_9fcc_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_29/bd_9fcc_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_30/bd_9fcc_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_1/bd_9fcc_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_1/bd_9fcc_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_2/bd_9fcc_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_2/bd_9fcc_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_3/bd_9fcc_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_3/bd_9fcc_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_4/bd_9fcc_arsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_5/bd_9fcc_rsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_6/bd_9fcc_awsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_7/bd_9fcc_wsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_8/bd_9fcc_bsw_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_12/bd_9fcc_s00a2s_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_13/bd_9fcc_sarn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_14/bd_9fcc_srn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_15/bd_9fcc_sawn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_16/bd_9fcc_swn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_17/bd_9fcc_sbn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_21/bd_9fcc_s01a2s_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_22/bd_9fcc_sarn_1_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_23/bd_9fcc_srn_1_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_24/bd_9fcc_m00s2a_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_25/bd_9fcc_m00arn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_26/bd_9fcc_m00rn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_27/bd_9fcc_m00awn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_28/bd_9fcc_m00wn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/bd_0/ip/ip_29/bd_9fcc_m00bn_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/bd/microBlaze/ip/microBlaze_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microBlaze_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
