# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/axi_ethernet_1.xci
# IP: The module: 'axi_ethernet_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/bd_9d5e_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0 || ORIG_REF_NAME==bd_9d5e_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_0/bd_9d5e_0_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_eth_buf_0 || ORIG_REF_NAME==bd_9d5e_0_eth_buf_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_1/bd_9d5e_0_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_mac_0 || ORIG_REF_NAME==bd_9d5e_0_mac_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_2/bd_9d5e_0_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_c_shift_ram_0_0 || ORIG_REF_NAME==bd_9d5e_0_c_shift_ram_0_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_3/bd_9d5e_0_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_c_counter_binary_0_0 || ORIG_REF_NAME==bd_9d5e_0_c_counter_binary_0_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_4/bd_9d5e_0_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_xlconstant_0_0 || ORIG_REF_NAME==bd_9d5e_0_xlconstant_0_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_5/bd_9d5e_0_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_util_vector_logic_0_0 || ORIG_REF_NAME==bd_9d5e_0_util_vector_logic_0_0} -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/bd_9d5e_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/axi_ethernet_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernet_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/synth/axi_ethernet_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernet_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/axi_ethernet_1.xci
# IP: The module: 'axi_ethernet_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/bd_9d5e_0.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0 || ORIG_REF_NAME==bd_9d5e_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_0/bd_9d5e_0_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_eth_buf_0 || ORIG_REF_NAME==bd_9d5e_0_eth_buf_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_1/bd_9d5e_0_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_mac_0 || ORIG_REF_NAME==bd_9d5e_0_mac_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_2/bd_9d5e_0_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_c_shift_ram_0_0 || ORIG_REF_NAME==bd_9d5e_0_c_shift_ram_0_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_3/bd_9d5e_0_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_c_counter_binary_0_0 || ORIG_REF_NAME==bd_9d5e_0_c_counter_binary_0_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_4/bd_9d5e_0_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_xlconstant_0_0 || ORIG_REF_NAME==bd_9d5e_0_xlconstant_0_0} -quiet] -quiet

# IP: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/ip/ip_5/bd_9d5e_0_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_9d5e_0_util_vector_logic_0_0 || ORIG_REF_NAME==bd_9d5e_0_util_vector_logic_0_0} -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/bd_0/bd_9d5e_0_ooc.xdc

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/axi_ethernet_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernet_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: x:/My Documents/SeniorDesign/CyberTap/CyberTap.srcs/sources_1/ip/axi_ethernet_1/synth/axi_ethernet_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernet_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
